### ISSUE TITLE
unable to build, missing dependency 'graceful'

### ISSUE THREAD

**Issue by irgendwr** [netlify/git-gateway#34]
git-gateway depends on https://github.com/netlify/netlify-commons/graceful but that was **deleted** in https://github.com/netlify/netlify-commons/pull/72 !

Seems crazy to me that that was just deleted without even looking at what depends on it.

Without that dependency one is unable to build the git-gateway so that definitely needs to be fixed.

**Comment by wmtpratikk** [comment]
any updates?
