### ISSUE TITLE
Additional github API endpoints?

### ISSUE THREAD

**Issue by Jinksi** [netlify/git-gateway#8]
**- Do you want to request a *feature* or report a *bug*?**

Feature

Are there any plans to add support for other github API endpoints e.g. [`/merges`](https://developer.github.com/v3/repos/merging/)?

**Comment by bdougie** [comment]
Hey @Jinksi curious to find out more about the use case for `/merges` and how users of the API could benefit.

**Comment by Jinksi** [comment]
Hi @bdougie,

This was related to https://github.com/simplajs/simpla/issues/84.
Simpla uses Github as a content repository, similar to Netlify CMS.
However, it updates content via `/merges` rather than `/pulls`.
