### ISSUE TITLE
GitLab support

### ISSUE THREAD

**Issue by jayvdb** [netlify/git-gateway#9]
Does this support GitLab?  Is that on the horizon?

**Comment by biilmann** [comment]
We would love to support GitLab and it should be fairly straight forward - main difference from the GitHub integration would be having to handle refresh tokens rather than just plain access tokens

**Comment by tech4him1** [comment]
@biilmann I've been testing GitLab's OAuth (standard [Web Application Flow](https://docs.gitlab.com/ce/api/oauth2.html#web-application-flow)), and even though it sends a refresh token along with the access token, the access token doesn't seem to expire. I'm not sure whether this is a setting that could be changed, but for now it seems that we don't need to worry about refresh tokens. Is your experience different there?

**Comment by erquhart** [comment]
The [example response] shows an expiry field - we'll probably want to provide for the expiration case even if the timing isn't clear cut.

**Comment by kobvel** [comment]
Any progress on this one?

**Comment by timaschew** [comment]
I'm confused.

If you check the current Readme it seems that GitLab works.

>Netlify’s Git Gateway lets you setup a gateway to your choice of Git provider's API ( now available with both GitHub and GitLab 🎉 ) that lets tools like Netlify CMS work with content, branches and pull requests on your users’ behalf.

So why this issues is not closed yet?  
Also this one: https://github.com/netlify/netlify-cms/issues/568

**Comment by tech4him1** [comment]
@timaschew You are correct, this issue should have been closed by #10.
